### ISSUE TITLE
running azure bus sampler  amqp over websocket not working in NON GUI mode.

### ISSUE THREAD

**Issue by tarung121** [pnopjp/jmeter-plugins#24]
Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: Connection refused: no further information, errorContext[NAMESPACE: ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: Connection refused: no further information, errorContext[NAMESPACE: ERROR CONTEXT: N/A]
 at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[jmeter-plugins-azure-servicebus-0.3.1.jar:?]
 at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:325)

NOTE- its working in GUI mode

**Comment by tarung121** [comment]
Its does not set proxy

**Comment by tarung121** [comment]
When set proxy in jmeter , in NON GUI mode its not picking that proxy settings

**Comment by kuniteru** [comment]
Hello tarung121,

In my environment I can send messages to Azure Service Bus.

Please elaborate on your environment and situation.

JMeter version: 
OS/distribution and version: 
Java runtime provider and version: 
If your OS is Linux, how you installed Java: 

JMeter GUI or CLI mode: (I am aware of problems with CLI, GUI is OK)
Are you using proxy?: (I am aware that you do not use it.)
Queue or Topic?: 
Protocol: (AMQP / AMQP over Web Sockets)
Auth type: 

Note that if you select "AMQP" for Protocol, you cannot use Proxy; if you want to use proxy, you must select "AMQP over Web Sockets".

**Comment by tarung121** [comment]
JMeter version: 5.6.3
OS/distribution and version: Windows 10 enterprise 10.0.19045 build 19045 
Java runtime provider and version: jre 17.0.5.8
If your OS is Linux, how you installed Java:

JMeter GUI or CLI mode: (I am aware of problems with CLI, GUI is OK) running using command line jmeter -n -t
Are you using proxy?: (I am aware that you do not use it.) yes i am using proxy so plugin dont able to use plugin
Queue or Topic?: queue
Protocol: (AMQP / AMQP over Web Sockets) - AMQP over Web Sockets
Auth type: shared access signature

Problem is plugin dont able to use proxy defined in jmeter or you pass in command line also using -H -P

**Comment by kuniteru** [comment]
Even if AMQP over Web Sockets was selected, when running in Cli mode, it would run as AMQP protocol, and Proxy was not being used accordingly.
Fixed in [Azure Service Bus Sampler v0.3.2](https://github.com/pnopjp/jmeter-plugins/releases/ASB0.3.2).
Thanks for your patience.
