### ISSUE TITLE
Can't read my secret from azure key vault

### ISSUE THREAD

**Issue by bhazied** [pnopjp/jmeter-plugins#25]
Hi, 
when I try to use this plugin, I got some problems
First, i saw this link https://learn.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests
But, its impossible to run teh test without having user.proprieties or jmeter.proprieties file.
Then, when i execute my test, and try to get my secret value, i got this error:
ERROR c.a.s.k.s.SecretClientBuilder: The Azure Key Vault url is malformed.

my key vault format as below :
https://<myVault>.vault.azure.net/secrets/<SecretName>/fddd089393db44c288ea422d8833df64 

thx

**Comment by kuniteru** [comment]
Hi,
The following five plug-ins are provided here
- jmeter-plugins-azure-eventhubs-0.2.5.jar
- jmeter-plugins-azure-load-testing-stub-0.1.0.jar
- jmeter-plugins-azure-servicebus-0.3.1.jar
- jmeter-plugins-azure-storage-queue-0.1.3.jar
- jmeter-plugins-functions-azure-0.4.4.jar

Which one do you use?

**Comment by bhazied** [comment]
Hi,
Thx for replay
I use jmeter-plugins-azure-load-testing-stub-0.1.0.jar

Le mar. 5 nov. 2024, 04 h 55, Kuniteru Asami ***@***.***> a
écrit :

**Comment by kuniteru** [comment]
Hi,

This plugin is a Stub that allows custom functions that are only available in Azure Load Testing to work in pure Azure JMeter™.
Enables Apache JMeter™ to use custom functions when creating and testing test scripts to be uploaded to Azure Load Testing.
It is not for use on Azure Load Testing.

If you wish to use this plugin with pure Apache JMeter™, please refer to the following documentation.
https://github.com/pnopjp/jmeter-plugins/blob/master/docs/azure-load-testing-stub.md

**Comment by bhazied** [comment]
This si exactly what i do.
I create my jmeter configuration, I added this plugin to use the __GetSecret() function.
I execute the jmeter jmx file with Azure load testing as showin on https://learn.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests
also, with jmx file, i upload user.proprietes file, this file content the configuration of storetype and auth type

Below the log :
2024-11-04 21:15:05,699 ERROR c.a.s.k.s.SecretClientBuilder: The Azure Key Vault url is malformed.
2024-11-04 21:15:05,700 ERROR j.c.p.j.f.GetSecret: Error calling __GetSecret function with Secret name "azureloadtestingsecret". java.lang.IllegalArgumentException: The Azure Key Vault url is malformed.
java.lang.IllegalArgumentException: The Azure Key Vault url is malformed.
	at com.azure.security.keyvault.secrets.SecretClientBuilder.vaultUrl(SecretClientBuilder.java:215) ~[jmeter-plugins-azure-load-testing-stub-0.1.0.jar:?]
	at jp.co.pnop.jmeter.functions.GetSecret.getKeyVaultSecret(GetSecret.java:175) ~[jmeter-plugins-azure-load-testing-stub-0.1.0.jar:?]
	at jp.co.pnop.jmeter.functions.GetSecret.execute(GetSecret.java:108) [jmeter-plugins-azure-load-testing-stub-0.1.0.jar:?]
	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:139) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.engine.util.CompoundVariable.execute(CompoundVariable.java:114) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.testelement.property.FunctionProperty.getStringValue(FunctionProperty.java:104) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.testelement.TestElement.get(TestElement.kt:276) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.config.Argument.getValue(Argument.java:154) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.config.Arguments.getArgumentsAsMap(Arguments.java:104) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.engine.PreCompiler.createArgumentsMap(PreCompiler.java:113) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jmeter.engine.PreCompiler.addNode(PreCompiler.java:100) [ApacheJMeter_core.jar:5.6.3]
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:1029) [jorphan.jar:5.6.3]
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:1012) [jorphan.jar:5.6.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:413) [ApacheJMeter_core.jar:5.6.3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.net.MalformedURLException: no protocol: 
	at java.base/java.net.URL.<init>(URL.java:674) ~[?:?]
	at java.base/java.net.URL.<init>(URL.java:569) ~[?:?]
	at java.base/java.net.URL.<init>(URL.java:516) ~[?:?]
	at com.azure.security.keyvault.secrets.SecretClientBuilder.vaultUrl(SecretClientBuilder.java:213) ~[jmeter-plugins-azure-load-testing-stub-0.1.0.jar:?]

**Comment by kuniteru** [comment]
This plugin cannot be used on Azure Load Testing.
This plugin is only for Apache JMeter installed on-premise or on a virtual machine.

azure_load_testing_stub.get_secret.{SECRET_NAME}.store_type and azure_load_testing_stub.get_secret.{SECRET_NAME}.auth_type set in user.profile, etc. are exclusive to this plugin and are not recognized by Azure Load Testing.
For Azure Load Testing, follow this page to set the secret.
https://learn.microsoft.com/ja-jp/azure/load-testing/how-to-parameterize-load-tests

This plugin is intended to use the same jmx files for pure Apache JMeter and Azure Load Testing.
The configuration method for referencing the secret is different for each environment.

**Comment by bhazied** [comment]
Thx for your return
